import Header from "@/components/layout/header/Header";
import "./globals.css";
import localFont from "next/font/local";

const bebasNeue = localFont({
  src: [
    {
      path: "./fonts/Bebas-Neue-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Bebas-Neue-Bold.ttf",
      weight: "500",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
