import Header from '@/components/layout/header/Header'
import { Roboto } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

const roboto = Roboto({
	variable: '--font-montserrat',
	weight: ['400', '500', '600', '700', '800'],
	subsets: ['cyrillic', 'cyrillic-ext'],
})

const bebasNeue = localFont({
	src: [
		{
			path: './fonts/Bebas-Neue-Regular.ttf',
			weight: '400',
			style: 'normal',
		},
		{
			path: './fonts/Bebas-Neue-Bold.ttf',
			weight: '500',
			style: 'normal',
		},
	],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${bebasNeue.variable}  ${roboto.variable} antialiased`}>
				<Header />
				{children}
			</body>
		</html>
	)
}
